<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config[
  <!ELEMENT lockss-config (if|property)+>
  <!ELEMENT property (property|list|value|if)*>
  <!ELEMENT list (value)+>
  <!ELEMENT value (#PCDATA)>
  <!ELEMENT test EMPTY>
  <!ELEMENT and (and|or|not|test)*>
  <!ELEMENT or (and|or|not|test)*>
  <!ELEMENT not (and|or|not|test)*>
  <!ELEMENT if (and|or|not|then|else|property)*>
  <!ELEMENT then (property)*>
  <!ELEMENT else (property)*>
  <!ATTLIST property name CDATA #REQUIRED>
  <!ATTLIST property value CDATA #IMPLIED>
  <!ATTLIST test hostname CDATA #IMPLIED>
  <!ATTLIST test group CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST test daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST test daemonVersion CDATA #IMPLIED>
  <!ATTLIST test platformVersionMin CDATA #IMPLIED>
  <!ATTLIST test platformVersionMax CDATA #IMPLIED>
  <!ATTLIST test platformVersion CDATA #IMPLIED>
  <!ATTLIST if hostname CDATA #IMPLIED>
  <!ATTLIST if group CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMin CDATA #IMPLIED>
  <!ATTLIST if daemonVersionMax CDATA #IMPLIED>
  <!ATTLIST if daemonVersion CDATA #IMPLIED>
  <!ATTLIST if platformVersionMin CDATA #IMPLIED>
  <!ATTLIST if platformVersionMax CDATA #IMPLIED>
  <!ATTLIST if platformVersion CDATA #IMPLIED>
]>

<lockss-config>

  <property name="org.lockss.title">

    <property name="Abacus33">
      <property name="title" value="Abacus Volume 33 (1997)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="33"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus34">
      <property name="title" value="Abacus Volume 34 (1998)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="34"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus35">
      <property name="title" value="Abacus Volume 35 (1999)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="35"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus36">
      <property name="title" value="Abacus Volume 36 (2000)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="36"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus37">
      <property name="title" value="Abacus Volume 37 (2001)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="37"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus38">
      <property name="title" value="Abacus Volume 38 (2002)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="38"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus39">
      <property name="title" value="Abacus Volume 39 (2003)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="39"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus40">
      <property name="title" value="Abacus Volume 40 (2004)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="40"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus41">
      <property name="title" value="Abacus Volume 41 (2005)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="41"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus42">
      <property name="title" value="Abacus Volume 42 (2006)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="42"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Abacus43">
      <property name="title" value="Abacus Volume 43 (2007)"/>
      <property name="journalTitle" value="Abacus"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="abac"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6281"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="43"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance38">
      <property name="title" value="Accounting &amp; Finance Volume 38 (1998)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="38"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance39">
      <property name="title" value="Accounting &amp; Finance Volume 39 (1999)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="39"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance40">
      <property name="title" value="Accounting &amp; Finance Volume 40 (2000)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="40"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance41">
      <property name="title" value="Accounting &amp; Finance Volume 41 (2001)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="41"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance42">
      <property name="title" value="Accounting &amp; Finance Volume 42 (2002)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="42"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance43">
      <property name="title" value="Accounting &amp; Finance Volume 43 (2003)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="43"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance44">
      <property name="title" value="Accounting &amp; Finance Volume 44 (2004)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="44"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance45">
      <property name="title" value="Accounting &amp; Finance Volume 45 (2005)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="45"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="Accounting&amp;Finance46">
      <property name="title" value="Accounting &amp; Finance Volume 46 (2006)"/>
      <property name="journalTitle" value="Accounting &amp; Finance"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="acfi"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-629X"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="46"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="AccountingForum23">
      <property name="title" value="Accounting Forum Volume 23 (1999)"/>
      <property name="journalTitle" value="Accounting Forum"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="accf"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6303"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="23"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="AccountingForum24">
      <property name="title" value="Accounting Forum Volume 24 (2000)"/>
      <property name="journalTitle" value="Accounting Forum"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="accf"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6303"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="24"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="AccountingForum25">
      <property name="title" value="Accounting Forum Volume 25 (2001)"/>
      <property name="journalTitle" value="Accounting Forum"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="accf"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6303"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="25"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="AccountingForum26">
      <property name="title" value="Accounting Forum Volume 26 (2002)"/>
      <property name="journalTitle" value="Accounting Forum"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="accf"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6303"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="26"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="AccountingForum27">
      <property name="title" value="Accounting Forum Volume 27 (2003)"/>
      <property name="journalTitle" value="Accounting Forum"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="accf"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1467-6303"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="27"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica43">
      <property name="title" value="Acta Anaesthesiologica Scandinavica Volume 43 (1999)"/>
      <property name="journalTitle" value="Acta Anaesthesiologica Scandinavica"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="aas"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1399-6576"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="43"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica44">
      <property name="title" value="Acta Anaesthesiologica Scandinavica Volume 44 (2000)"/>
      <property name="journalTitle" value="Acta Anaesthesiologica Scandinavica"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="aas"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1399-6576"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="44"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica45">
      <property name="title" value="Acta Anaesthesiologica Scandinavica Volume 45 (2001)"/>
      <property name="journalTitle" value="Acta Anaesthesiologica Scandinavica"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="aas"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1399-6576"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="45"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica46">
      <property name="title" value="Acta Anaesthesiologica Scandinavica Volume 46 (2002)"/>
      <property name="journalTitle" value="Acta Anaesthesiologica Scandinavica"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="aas"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1399-6576"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="46"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica47">
      <property name="title" value="Acta Anaesthesiologica Scandinavica Volume 47 (2003)"/>
      <property name="journalTitle" value="Acta Anaesthesiologica Scandinavica"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="aas"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1399-6576"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="47"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica48">
      <property name="title" value="Acta Anaesthesiologica Scandinavica Volume 48 (2004)"/>
      <property name="journalTitle" value="Acta Anaesthesiologica Scandinavica"/>
      <property name="plugin" value="org.lockss.plugin.blackwell.BlackwellPlugin"/>
      <property name="param.1">
	<property name="key" value="base_url"/>
	<property name="value" value="http://www.blackwell-synergy.com/"/>
      </property>
      <property name="param.2">
	<property name="key" value="journal_id"/>
	<property name="value" value="aas"/>
      </property>
      <property name="param.3">
	<property name="key" value="journal_issn"/>
	<property name="value" value="1399-6576"/>
      </property>
      <property name="param.4">
	<property name="key" value="volume_name"/>
	<property name="value" value="48"/>
      </property>
      <property name="attributes.publisher" value="Blackwell Publishing"/>
    </property>

    <property name="ActaAnaesthesiologicaScandinavica49">